theme: jekyll-theme-minimal
title: "From Credits to Critiques: Gender Influence Shaping Movie Success"
description: An attempt to show how gender influences film success across traditional and streaming platforms
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
